language: ruby
cache:
  - apt
  - bundler
bundler_args: --jobs 4 --retry 4 --without development --path vendor/bundle
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
  - rbx
env:
  - VERSION=5.09 SHA1=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=gcc
  - VERSION=5.09 SHA1=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=clang
  - VERSION=5.14 SHA1=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=gcc
  - VERSION=5.14 SHA1=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=clang
  - VERSION=5.18 SHA1=8753e72097f2cc935608e3b1c57c4c4e31bd8d21 COMPILER=gcc
  - VERSION=5.18 SHA1=8753e72097f2cc935608e3b1c57c4c4e31bd8d21 COMPILER=clang
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
branches:
  only:
    - master
before_script:
  - export CC=$COMPILER
  - travis_retry curl -L -s http://git.io/lJJQIw > libmagic.sh
  - travis_retry sudo VERSION=$VERSION SHA1=$SHA1 CC=$COMPILER bash libmagic.sh
script:
  - export CC=$COMPILER
  - bundle exec rake test
