language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
branches:
  only:
    - master
before_script:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --force-yes -y libmagic1 libmagic-dev
script: rake test
