language: ruby
dist: precise

cache:
  - apt
  - bundler

bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - rbx-2

env:
  matrix:
    - VERSION=5.09 SHA1=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=gcc
    - VERSION=5.09 SHA1=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=clang
    - VERSION=5.14 SHA1=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=gcc
    - VERSION=5.14 SHA1=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=clang
    - VERSION=5.18 SHA1=8753e72097f2cc935608e3b1c57c4c4e31bd8d21 COMPILER=gcc
    - VERSION=5.18 SHA1=8753e72097f2cc935608e3b1c57c4c4e31bd8d21 COMPILER=clang
    - VERSION=5.25 SHA1=fea78106dd0b7a09a61714cdbe545135563e84bd COMPILER=gcc
    - VERSION=5.25 SHA1=fea78106dd0b7a09a61714cdbe545135563e84bd COMPILER=clang
    - VERSION=5.32 SHA1=c2858a8043387d1229d8768ad42762a803d017db COMPILER=gcc
    - VERSION=5.32 SHA1=c2858a8043387d1229d8768ad42762a803d017db COMPILER=clang
    - VERSION=5.33 SHA1=31a67e4dc0a3d7a8d1b850429c3f625314700240 COMPILER=gcc
    - VERSION=5.33 SHA1=31a67e4dc0a3d7a8d1b850429c3f625314700240 COMPILER=clang

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

branches:
  only:
    - master
    - development

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - export CC=$(which $COMPILER)
  - sudo -H -E -n VERSION=$VERSION SHA1=$SHA1 CC=$CC PATH=$PATH scripts/libmagic.sh

before_script:
  - bundle exec rake clean clobber

script:
  - bundle exec rake test
