language: ruby
dist: xenial

cache:
  bundler: true
  directories:
    - "${HOME}/cache"

bundler_args: --jobs 3 --retry 5

rvm:
  - '2.5'
  - '2.6'
  - '2.7'
  - '3.0'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: '3.0'

branches:
  only:
    - main

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - gem install bundler
  - bundle config set --local path 'vendor/bundle'
  - bundle config set --local without 'development'

before_script:
  - export CFLAGS="-I${PREFIX}/include" LDFLAGS="-L${PREFIX}/lib"
  - export LD_LIBRARY_PATH="${PREFIX}/lib"
  - bundle exec rake clean

script:
  - bundle exec rake compile
  - bundle exec rake test
