language: ruby
dist: precise

cache:
  - apt
  - bundler

bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - ruby-head
  - rbx-2

env:
  - VERSION=5.09 SHA1=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=gcc
  - VERSION=5.09 SHA1=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=clang
  - VERSION=5.14 SHA1=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=gcc
  - VERSION=5.14 SHA1=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=clang
  - VERSION=5.18 SHA1=8753e72097f2cc935608e3b1c57c4c4e31bd8d21 COMPILER=gcc
  - VERSION=5.18 SHA1=8753e72097f2cc935608e3b1c57c4c4e31bd8d21 COMPILER=clang
  - VERSION=5.25 SHA1=fea78106dd0b7a09a61714cdbe545135563e84bd COMPILER=gcc
  - VERSION=5.25 SHA1=fea78106dd0b7a09a61714cdbe545135563e84bd COMPILER=clang
  - VERSION=5.31 SHA1=d66f71fb29ec0e9cecbefe9d7433d7a315f3302c COMPILER=gcc
  - VERSION=5.31 SHA1=d66f71fb29ec0e9cecbefe9d7433d7a315f3302c COMPILER=clang

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

branches:
  only:
    - master
    - development

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - export CC=$(which $COMPILER)
  - export URL="https://gist.githubusercontent.com/kwilczynski/9270161/raw/2a4946c0b745b2bfdd124a14c1290d1290ebf64c/libmagic.sh"
  - curl -L -s $URL > libmagic.sh
  - sudo -H -E VERSION=$VERSION SHA1=$SHA1 CC=$CC PATH=$PATH bash libmagic.sh

before_script:
  - bundle exec rake clean clobber

script:
  - bundle exec rake test
