language: ruby
cache:
  - apt
bundler_args: --jobs 4 --retry 2
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
  - rbx-19mode
env:
  - VERSION=5.09 CHECKSUM=9d905f9e50033c3f5be3728473cbb709a41550fb COMPILER=gcc
  - VERSION=5.14 CHECKSUM=064c8f17a5f7ae1e336a9285131e046d3b2d04d7 COMPILER=gcc
  - VERSION=5.17 CHECKSUM=f7e837a0d3e4f40a02ffe7da5e146b967448e0d8 COMPILER=gcc
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
branches:
  only:
    - master
before_script:
  - export CC=$COMPILER
  - travis_retry curl -L -s http://git.io/Zey2LA > libmagic.sh
  - travis_retry sudo VERSION=$VERSION CHECKSUM=$CHECKSUM CC=$COMPILER bash libmagic.sh
script: rake test
